defaults:
  - model: deepspeech2
  - metrics: beam_argmax
  - datasets: inference # we do not want to run inference on training data
  - dataloader: example
  - transforms: example_only_instance
  - _self_
text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
  vocab_path: src/lm/librispeech-vocab.txt
  lm_path: src/lm/3-gram.pruned.1e-7.arpa
  beam_search: True
inferencer:
  device_tensors: ["spectrogram", "text_encoded"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "preds" # any name here, can be a dataset name
  seed: 1
  beam_search: True
  beam_size: 5
  from_pretrained: "saved/testing/model_best.pth" # path to the pretrained model
